#!/usr/bin/env python3
"""
Fetches WoW item icons from Blizzard API for all items in items.ts.
Outputs src/data/itemIcons.ts with a name→iconUrl mapping.

Usage: python3 scripts/fetch_icons.py
"""

import re
import json
import time
import requests
from concurrent.futures import ThreadPoolExecutor, as_completed

CLIENT_ID     = "6c8f3c33a9e347759056401b7ecdad4d"
CLIENT_SECRET = "mmkTMJy1qixbI5txegxYD1SJ9K6Pnuu6"
REGION        = "eu"
TOKEN_URL     = "https://oauth.battle.net/token"
API_BASE      = f"https://{REGION}.api.blizzard.com"

# ── Auth ──────────────────────────────────────────────────────────────────────

def get_token() -> str:
    r = requests.post(TOKEN_URL, data={"grant_type": "client_credentials"},
                      auth=(CLIENT_ID, CLIENT_SECRET))
    r.raise_for_status()
    return r.json()["access_token"]

TOKEN = get_token()
HEADERS = {"Authorization": f"Bearer {TOKEN}"}

def api(path: str, params: dict = {}) -> dict:
    base = {"namespace": f"static-{REGION}", "locale": "fr_FR"}
    r = requests.get(f"{API_BASE}{path}", headers=HEADERS, params={**base, **params})
    if r.status_code == 404:
        return {}
    r.raise_for_status()
    return r.json()

# ── Parse item names from items.ts ───────────────────────────────────────────

def extract_names(path: str) -> list[str]:
    text = open(path, encoding="utf-8").read()
    # Items use either double or single quotes for name+source
    dq = re.findall(r'\["([^"]+)",\s*"[^"]+",\s*\'(?:epic|legendary|rare|uncommon)\'', text)
    sq = re.findall(r"\['([^']+)',\s*'[^']+',\s*'(?:epic|legendary|rare|uncommon)'", text)
    all_names = dq + sq
    return list(dict.fromkeys(all_names))  # deduplicate, preserve order

# ── Fetch icon for one item name ──────────────────────────────────────────────

def fetch_icon(name: str) -> tuple[str, str | None]:
    # 1. Search by French name
    data = api("/data/wow/search/item", {
        "name.fr_FR": name,
        "_pageSize": "3",
        "orderby": "id:desc",
    })
    results = data.get("results", [])
    if not results:
        return name, None

    # Pick best match (exact name match preferred)
    item_id = None
    for r in results:
        found = r.get("data", {}).get("name", {}).get("fr_FR", "")
        if found.lower() == name.lower():
            item_id = r["data"]["id"]
            break
    if item_id is None:
        item_id = results[0]["data"]["id"]

    # 2. Fetch media
    media = api(f"/data/wow/media/item/{item_id}", {"namespace": f"static-{REGION}"})
    assets = media.get("assets", [])
    for asset in assets:
        if asset.get("key") == "icon":
            return name, asset["value"]

    return name, None

# ── Main ──────────────────────────────────────────────────────────────────────

ITEMS_TS = "src/data/items.ts"
OUT_TS   = "src/data/itemIcons.ts"

names = extract_names(ITEMS_TS)
print(f"Found {len(names)} unique items to fetch icons for...")

icons: dict[str, str] = {}
failed: list[str] = []

with ThreadPoolExecutor(max_workers=12) as pool:
    futures = {pool.submit(fetch_icon, n): n for n in names}
    done = 0
    for fut in as_completed(futures):
        name, url = fut.result()
        done += 1
        if url:
            icons[name] = url
            print(f"  ✓ [{done}/{len(names)}] {name}")
        else:
            failed.append(name)
            print(f"  ✗ [{done}/{len(names)}] NOT FOUND: {name}")

print(f"\n✅ {len(icons)} icons found, ❌ {len(failed)} not found")
if failed:
    print("Not found:")
    for n in failed:
        print(f"  - {n}")

# Write TypeScript output
lines = ["// Auto-generated by scripts/fetch_icons.py — do not edit manually",
         "export const ITEM_ICONS: Record<string, string> = {"]
for name, url in sorted(icons.items()):
    escaped = name.replace("'", "\\'")
    lines.append(f"  '{escaped}': '{url}',")
lines.append("}")

open(OUT_TS, "w", encoding="utf-8").write("\n".join(lines) + "\n")
print(f"\nWritten to {OUT_TS}")
